coverage:
  precision: 2
  round: down
  range: "25...100"
  status:
    project:
      default:
        target: 25%
        threshold: 3%
    patch:
      default:
        target: 20%
        threshold: 10%

ignore:
  - "test/**/*"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/generated_plugin_registrant.dart"
  - "lib/l10n/**"
